name: Update Demo Website

on:
  push:
    branches:
      - "master"

jobs:
  test:
    name: Install and Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: jekyll-action action
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'gh-pages'
          jekyll_build_options: '-b personal-website'
        env:
          JEKYLL_DEBUG: true
          PAGES_REPO_NWO: 'better-personal-website/personal-website'